//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeDetailsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetailsTable()
        {
            this.ProjectDetailsTables = new HashSet<ProjectDetailsTable>();
            this.TechnologyDetailsTables = new HashSet<TechnologyDetailsTable>();
        }
    
        public int EmployeeID { get; set; }
        [Required(ErrorMessage = "Please enter Employee_FirstName.")]
        public string Employee_FirstName { get; set; }
        [Required(ErrorMessage = "Please enter Employee_LastName.")]
        public string Employee_LastName { get; set; }
        [Required(ErrorMessage = "Please enter Employee_Age.")]
        [Range(20, 45, ErrorMessage ="Age Should Be Between 20 and 45")]
        public int Employee_Age { get; set; }
        [Required(ErrorMessage = "Please Select Employee_Gender.")]
        public string Employee_Gender { get; set; }
        [Required(ErrorMessage = "Please enter Employee_Address.")]
        public string Employee_Address { get; set; }
        [Required(ErrorMessage = "Please enter Employee_Phone.")]
        public string Employee_Phone { get; set; }
        [Required(ErrorMessage = "Please Select Employee_State.")]
        public string Employee_State { get; set; }
        [Required(ErrorMessage = "Please enter Employee_Designation.")]
        public string Employee_Designation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailsTable> ProjectDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologyDetailsTable> TechnologyDetailsTables { get; set; }
    }
}
