//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCompanyDBEntities : DbContext
    {
        public ITCompanyDBEntities()
            : base("name=ITCompanyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeDetailsTable> EmployeeDetailsTables { get; set; }
        public virtual DbSet<ProjectDetailsTable> ProjectDetailsTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TechnologyDetailsTable> TechnologyDetailsTables { get; set; }
        public virtual DbSet<AdminCredentialsTable> AdminCredentialsTables { get; set; }
    }
}
